// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var extractMeowed, getHelpText, getOptions, log, olog, throwErrorOnUsageFail;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("cliargumentsmodule"));

import meow from 'meow';

//#############################################################
//region internal functions
getHelpText = function() {
  log("getHelpText");
  return `Usage 
    $ kraken-csv-to-xml transactions.csv
    
Options
    required: arg1, --input-file, -i
        the path to the csv file to read and translate

    optional: arg2, --output-file, -i
        the path to the xml file to be written.
        if it is not defined we will write the output as <input-file-name>.xml 

Examples
    $ kraken-csv-to-xml transactions.csv
    ...`;
};

getOptions = function() {
  log("getOptions");
  return {
    importMeta: import.meta,
    flags: {
      inputFile: {
        type: "string", // or string
        alias: "i"
      },
      outputFile: {
        type: "string",
        alias: "o"
      }
    }
  };
};

//#############################################################
extractMeowed = function(meowed) {
  var inputFile, output, outputFile;
  log("extractMeowed");
  inputFile = null;
  outputFile = null;
  if (meowed.input[0]) {
    inputFile = meowed.input[0];
  }
  if (meowed.flags.inputFile) {
    inputFile = meowed.flags.inputFile;
  }
  if (meowed.input[1]) {
    outputFile = meowed.input[1];
  }
  if (meowed.flags.outputFile) {
    output = meowed.flags.outputFile;
  }
  return {inputFile, outputFile};
};

throwErrorOnUsageFail = function(extract) {
  log("throwErrorOnUsageFail");
  if (!extract.inputFile) {
    throw new Error("Usag error: no input-file has been defined!");
  }
};

//endregion

//#############################################################
export var extractArguments = function() {
  var extract, meowed;
  log("extractArguments");
  meowed = meow(getHelpText(), getOptions());
  extract = extractMeowed(meowed);
  throwErrorOnUsageFail(extract);
  return extract;
};
