// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var createResonableJSON, log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

import papa from "papaparse";

import pathModule from "path";

import fs from "fs";

import * as js2xml from "js2xmlparser";

import * as cfg from "./configmodule.js";

//#############################################################################
export var execute = function(e) {
  var csvString, inputPath, outputPath, result, resultJSON, resultXML;
  log("execute");
  olog(e);
  inputPath = pathModule.resolve(e.inputFile);
  if (e.outputFile != null) {
    outputPath = pathModule.resolve(e.outputPath);
  } else {
    outputPath = inputPath + ".xml";
  }
  csvString = fs.readFileSync(inputPath, "utf8");
  // log csvString
  result = papa.parse(csvString);
  // olog result.data
  resultJSON = createResonableJSON(result.data);
  resultXML = js2xml.parse("transaction", resultJSON);
};

// olog resultXML
createResonableJSON = function(data) {
  var head;
  log("createResonableJSON");
  //#TODO structure data to reasonable json
  olog(data);
  head = data.shift();
  olog(head);
};
