// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var errLog, log, olog, successLog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("startupmodule"));

import c from 'chalk';

import * as mp from "./mainprocessmodule.js";

import * as ca from "./cliargumentsmodule.js";

//endregion

//#############################################################################
//region internal variables
errLog = function(arg) {
  return console.log(c.red(arg));
};

successLog = function(arg) {
  return console.log(c.green(arg));
};

//endregion

//#############################################################################
export var cliStartup = async function() {
  var e, err;
  log("cliStartup");
  try {
    e = ca.extractArguments();
    await mp.execute(e);
    return printSuccess('All done!');
  } catch (error) {
    err = error;
    printError("Error!");
    printError(err);
    if (err.stack) {
      printError(err.stack);
    }
    return process.exit(-1);
  }
};
